#!/bin/bash

# Usage message
if [ "$#" -ne 1 ]; then
  echo "Usage: ./run_parser.sh <input_file>"
  exit 1
fi

# Input file with source code
INPUT_FILE=$1

# Check if the input file exists
if [ ! -f "$INPUT_FILE" ]; then
  echo "Error: File '$INPUT_FILE' not found."
  exit 1
fi

# Run the lexer and parser
echo "Running lexer and parser on $INPUT_FILE..."

# Run the lexer and capture its output in a variable
TOKENS=$(python3 lexer_2.py "$INPUT_FILE")

# Check if lexer ran successfully
if [ $? -ne 0 ]; then
  echo "Lexer failed."
  exit 1
fi

# Step 2: Run the parser to generate the AST
# Assuming parser.py is your parser script which reads tokens from tokens.txt
echo "$TOKENS" | python3 parser.py "$TOKENS"

# Check if parser ran successfully
if [ $? -ne 0 ]; then
  echo "Parser failed."
  exit 1
fi

# Print result of AST generation
echo "AST generated by the parser."
